"""Initial migration

Revision ID: 891d0b54ae43
Revises: 
Create Date: 2025-12-22 12:43:34.960720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891d0b54ae43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['game_developer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('gamer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gamer_id')
    )
    op.create_table('gamer_game',
    sa.Column('gamer_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamer.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamer_game')
    op.drop_table('profile')
    op.drop_table('game')
    op.drop_table('gamer')
    op.drop_table('game_developer')
    # ### end Alembic commands ###
