"""add column country to gamedevelopper

Revision ID: d25fb212aa97
Revises: 891d0b54ae43
Create Date: 2025-12-22 12:44:59.030331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25fb212aa97'
down_revision = '891d0b54ae43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_developer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_developer', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
