"""add colum country to brand

Revision ID: 16a8437660f1
Revises: 0d08e428df04
Create Date: 2025-12-21 19:40:31.422119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a8437660f1'
down_revision = '0d08e428df04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbrand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbrand', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
