"""add column year to model

Revision ID: 43d98110594d
Revises: 16a8437660f1
Create Date: 2025-12-21 19:44:54.609537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d98110594d'
down_revision = '16a8437660f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carmodel', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
